SELECT * FROM CUSTOMER;
SELECT * FROM CUSTOMER WHERE (AGE<30)AND(SALARY>1000.00);
UPDATE CUSTOMER SET SALARY=10000.00 WHERE(ID=4);
DELETE FROM CUSTOMER WHERE(ID=2);
SELECT * FROM sys Tables;
SELECT * FROM ORDERS;
SELECT * FROM ORDERS WHERE (CUSTOMER_ID=3);

