CREATE TABLE `CUSTOMER` (
  `ID` int NOT NULL,
  `NAME` varchar(20) NOT NULL,
  `AGE` int NOT NULL,
  `ADDRESS` char(25) DEFAULT NULL,
  `SALARY` decimal(18,2) DEFAULT NULL,
  PRIMARY KEY (`ID`)
);

CREATE TABLE `INVOICE_ITEMS` (
  `ID_INVOICE` int NOT NULL,
  `ID_ITEM`  int NOT NULL,
  `COD_PROD` int NOT NULL,
  `VALUE_UNIT` decimal(18,2) DEFAULT NULL,
  `QUANTITY`  int NOT NULL,
  `DISCOUNT`  int NOT NULL,
  
  PRIMARY KEY (`ID_INVOICE`, `ID_ITEM`)
);



CREATE TABLE `ORDERS` (
  `ID` int NOT NULL,
  `DATE` datetime DEFAULT NULL,
  `CUSTOMER_ID` int DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `CUSTOMER_ID` (`CUSTOMER_ID`),
  CONSTRAINT `orders_ibfk_1` FOREIGN KEY (`CUSTOMER_ID`) REFERENCES `CUSTOMER` (`ID`)
) ;